"""empty message

Revision ID: 108e69443f0c
Revises: 4f62b677debe
Create Date: 2024-02-06 20:33:01.585020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108e69443f0c'
down_revision = '4f62b677debe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['employee_id'], ['id'])
        batch_op.drop_column('employee_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
