"""empty message

Revision ID: b2aea243f693
Revises: bb52498c8c26
Create Date: 2024-01-29 19:49:51.378370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2aea243f693'
down_revision = 'bb52498c8c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_to_departments', sa.String(), nullable=True))
        batch_op.drop_column('visible_departments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_departments', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('visible_to_departments')

    # ### end Alembic commands ###
