"""empty message

Revision ID: dbf350976793
Revises: b2aea243f693
Create Date: 2024-01-29 20:44:04.122627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf350976793'
down_revision = 'b2aea243f693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departments', sa.String(), nullable=True))
        batch_op.drop_column('visible_to_departments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_to_departments', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('departments')

    # ### end Alembic commands ###
